apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: workshop-scoreboard-template
  annotations:
    description: "Workshop Scoreboard Template"
    iconClass: "icon-openshift"
    tags: "workshop"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: workshop-scoreboard-client
    namespace: workshop-scoreboard-client
  spec:
    selector: 
      matchLabels:
        app: workshop-scoreboard-client
    template:
      metadata:
        labels:
          app: workshop-scoreboard-client
      spec:
        containers:
        - env:  
          - name: NUMBER_OF_USERS
            value: ${NUMBER_OF_USERS}
          - name: SCOREBOARD_SERVER
            value: ${SCOREBOARD_SERVER}
          - name: WORKSHOP_NAME
            value: ${WORKSHOP_NAME}
          image: quay.io/akrohg/workshop-scoreboard-client
          name: workshop-scoreboard-client
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: scoreboard-client-admin
  subjects:
    - kind: ServiceAccount
      name: default
      namespace: workshop-scoreboard-client
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
parameters:
- description: Number of users
  name: NUMBER_OF_USERS
  required: true
- description: Scoreboard Server URL
  name: SCOREBOARD_SERVER
  required: true
- description: Workshop Name
  name: WORKSHOP_NAME
  required: true