- name: Get project info
  block:
    - name: Check for workshop project
      k8s_info:
        kind: Namespace
        name: workshop
      register: _workshop_project

    - name: Set project fact if the project exists
      set_fact:
        project_status: "success"
        cacheable: yes
      when: _workshop_project.resources
  when: project_status is not defined

- name: Get MongoDB info
  block:
    - name: Check for MongoDB Service
      k8s_info:
        name: mongodb
        namespace: workshop
        kind: Service
      register: _mongodb_service

    - name: Set MongoDB fact if service exists
      set_fact:
        mongodb_status: "success"
        cacheable: yes
      when: _mongodb_service.resources
  when: mongodb_status is not defined

- name: Get Ratings API info
  block:
    - name: Check for ratings-api Service
      k8s_info:
        name: rating-api
        namespace: workshop
        kind: Service
      register: _ratings_api_service

    - name: Set Ratings API fact if service exists
      set_fact:
        rating_api_status: "success"
        cacheable: yes
      when: _ratings_api_service.resources
  when: rating_api_status is not defined

- name: Get Ratings frontend info
  block:
    - name: Check for rating-web Service
      k8s_info:
        name: rating-web
        namespace: workshop
        kind: Service
      register: _ratings_web_service

    - name: Set Ratings Frontend fact if service exists
      set_fact:
        rating_web_status: "success"
        cacheable: yes
      when: _ratings_web_service.resources
  when: rating_web_status is not defined

- name: Get NetworkPolicy info
  block:
    - name: Check for NetworkPolicy
      k8s_info:
        name: api-allow-from-web
        namespace: workshop
        kind: NetworkPolicy
        api_version: networking.k8s.io/v1
      register: _ratings_network_policy

    - name: Set NetworkPolicy fact if it exists
      set_fact:
        network_policy_status: "success"
        cacheable: yes
      when: _ratings_network_policy.resources
  when: network_policy_status is not defined

- name: Store cluster task results
  set_fact:
    lab1_tasks:
      - module: "0"
        status: success
      - module: "0"
        status: "{{ project_status | default('pending') }}"
      - module: "0"
        status: "{{ mongodb_status | default('pending') }}"
      - module: "0"
        status: "{{ rating_api_status | default('pending') }}"
      - module: "0"
        status: "{{ rating_web_status | default('pending') }}"
      - module: "0"
        status: "{{ network_policy_status | default('pending') }}"
