- name: Get parksmap deployments
  k8s_info:
    kind: Deployment
    label_selectors:
      - component = parksmap
      - app = workshop
      - role = frontend
  register: first_container_result

- name: Get first_container_statuses
  ansible.builtin.debug:
    msg: todo

- name: Get scaling_statuses
  ansible.builtin.debug:
    msg: todo

# Need to build full dictionary here that looks like this:
# [
#   {
#      attendeeName: "user1",
#      workshopTasks: [
#        {
#          module: "0"
#          status: "success"
#        }
#       ...
#      ]
#   }
#    ...
# ]
#
# So we're basically uploading attendee statuses in bulk. This will require a new endpoint on the server.
#
- name: Store workshop task results
  ansible.builtin.set_fact:
    workshop_tasks:
      - module: "0"
        status: "{{ first_container_status | default('pending') }}"
      - module: "0"
        status: "{{ scaling_status | default('pending') }}"
      - module: "0"
        status: "{{ expose_status | default('pending') }}"
      - module: "0"
        status: "{{ rbac_status | default('pending') }}"
      - module: "0"
        status: "{{ deploy_code_status | default('pending') }}"
      - module: "0"
        status: "{{ database_status | default('pending') }}"
      - module: "0"
        status: "{{ probe_status | default('pending') }}"
      - module: "0"
        status: "{{ pipeline_status | default('pending') }}"
      - module: "0"
        status: "{{ webhook_status | default('pending') }}"
      - module: "0"
        status: "{{ template_status | default('pending') }}"
      - module: "0"
        status: "{{ binary_status | default('pending') }}"
