name: Build and push
on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push to quay.io
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Build and push container images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
          repository: akrohg/cs-workshop-scoreboard-client
          tags: latest
          add_git_labels: true
