name: Build and push
on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push to quay.io
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Build and push container images
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          tags: quay.io/akrohg/cs-workshop-scoreboard-client:latest
          push: true
          file: Containerfile
